name: ClickSigns
main: me.IdioticAussie.ClickSigns
version: 1.2
author: IdioticAussie

depend: [Vault]

commands:
  clicksigns:
    description: Basic information
  signsetup:
    description: Tells the user how to setup a ClickSign
  effects:
    description: Lists the different effects 
    